### ISSUE TITLE
Parece não funcionar

### ISSUE THREAD

**Issue by tiagocaus** [gmgomess/jQuery-CPF-CNPJ-Validator-plugin#13]
Olá, fiz o teste e parece que não esta funcionando.

Veja nesse link https://jsfiddle.net/xLg7qp3w/

Tem algo que estou fazendo errado?

**Comment by gmgomess** [comment]
Olá @tiagocaus @hostcia 

O link referenciando diretamente o arquivo no github não irá enxergar o plugin.

Tente usar diretamente o conteúdo (download ou conteúdo do plugin).

Dê uma olhada: https://jsfiddle.net/r3hw58dg/ apenas adicionei o conteúdo do plugin ao seu js

**Comment by tiagocaus** [comment]
Entendi, irei fazer.
Uma pergunta, como fazer para que não seja necessário clicar no botão para submeter a validação.

Validar automaticamente quando sair do campo.
