### ISSUE TITLE
Erro na mascara do CPF

### ISSUE THREAD

**Issue by hostcia** [gmgomess/jQuery-CPF-CNPJ-Validator-plugin#14]
Ao digitar o CNPJ tudo certo, mas a mascara do CPF fica errada.

Fica assim ao digitar o décimo digito: `55.599.691/09`.

CPF completo: `55.599.691/098`

**Comment by victormatheusdev** [comment]
Mesmo problema

**Comment by gmgomess** [comment]
@victormaths esse issue já foi corrigido em janeiro. Está utilizando a ultima versão?
