### ISSUE TITLE
Função valida CPF com todos os números iguais

### ISSUE THREAD

**Issue by guilhermeocosta** [gmgomess/jQuery-CPF-CNPJ-Validator-plugin#5]
Inputar ```'000.000.000-00', '111.111.111-11', ...``` passa pelo validador!

**Comment by HelenDias** [comment]
Olá!
Para corrigir isso, usei regex, na função que eu chamava no PHP.
Vou postá-la como exemplo, em um novo arquivo aqui.
Se você ainda se encontra com erro nisso, talvez te ajude :D

**Comment by joesilver13** [comment]
Pessoal bom dia,
este validador não funciona.

**Comment by gmgomess** [comment]
Obrigado pelo aviso @guilhermeocosta 

Script corrigido.

Desculpe pela demora rs
