### ISSUE TITLE
Não consegue distinguir CPF/CNPJ no mesmo campo

### ISSUE THREAD

**Issue by fgsants** [gmgomess/jQuery-CPF-CNPJ-Validator-plugin#8]
Boa tarde Pessoal. 

Estou tentando usar este plugin para validar um campo (CPF/CNPJ), porém a função cpfcnpj reconhece apenas CPF, se eu continuar a digitar um CNPJ o mesmo não é reconhecido. Outra questão é que se usar a opção mask ele adiciona maxlenght=15 ao input (ao invés de 19).

Segue código utilizado:
	$('#cpfcnpj').cpfcnpj({
		mask: true, 
		validate: 'cpfcnpj', 
		event: 'keypress', 
		ifValid: function () {
			$('#cpfcnpj').next('i').remove();
			$('#cpfcnpj').attr('data-verify', "checked");
			$('#cpfcnpj').parent('label').removeClass('error');}, 
		ifInvalid: function () {
			$('#cpfcnpj').focus();
			$('#cpfcnpj').next('i').remove();
			$('<i>' + 'CPF/CNPF Inválido' + '</i>').insertAfter('#cpfcnpj');
			$('#cpfcnpj').attr('data-verify', "");
			$('#cpfcnpj').parent('label').addClass('error'); }
	});

**Comment by andrekutianski** [comment]
estou com o mesmo problema

**Comment by gmgomess** [comment]
Boa noite,

Corrigi esse ponto do script. 
Utilize a nova versão e qualquer problema me avise. 
Se houver qualquer mensagem no console também poste aqui. 
Obrigado
